
import java.awt.*;
import java.util.Random;
import javax.swing.*;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame1.java
 *
 * Created on Jul 21, 2011, 6:52:16 PM
 */
/**
 *
 * @author maxknee1
 */
public class NewJFrame1 extends javax.swing.JFrame {
    ImageIcon[] cardHolder = new ImageIcon[51];

    /** Creates new form NewJFrame1 */
    public NewJFrame1() {
        setLayout(new GridLayout(1,5));
        buildCards(cardHolder);
        Random random = new Random();
        int rand1 = random.nextInt(52 - 1) + 1;
        int rand2 = random.nextInt(52 - 1) + 1;
        int rand3 = random.nextInt(52 - 1) + 1;
        add(new JButton(cardHolder[rand1]));
       add(new JLabel(cardHolder[rand2]));
       add(new JLabel(cardHolder[rand3]));
       add(new JButton(cardHolder[2]));

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static void buildCards(ImageIcon[] cardHolder){
        for (int i = 0; i < 51; i++){ 
            cardHolder[i] = new ImageIcon("cards/" + (i + 1) + ".png");
        }
    }  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    NewJFrame1 frame = new NewJFrame1();
    frame.setTitle("card Game");
    frame.setSize(300, 300);
    frame.setLocationRelativeTo(null);
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    frame.setVisible(true);

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

